### ISSUE TITLE
Custom Certificate Compatibility

### ISSUE THREAD

**Issue by rgvalguna** [themesalmond/moodle-theme_almondb#14]
Hello, May I ask what is the problem here? I am newbie to this moodle. I installed Custom Certificate plugin with Almondb theme already installed. I ask if almondb compatible with Custom Certificate plugin. Thanks

![image](https://user-images.githubusercontent.com/29268824/200717418-f37dbe0f-bfe9-47f1-b34b-d328c22f7adb.png)

![image](https://user-images.githubusercontent.com/29268824/200719796-ff074c27-a8e8-4d6f-867c-d9fd3c83c4be.png)

**Comment by themesalmond** [comment]
Hello,
As far as we can see from the given errors, it seems that the error is "syntax error". Could you name the button in Block 1 using a character that should not be used? Please check the text you wrote to "Block 1 button" in Block 1 settings in theme settings.

**Comment by themesalmond** [comment]
Hello,
As far as we can see from the given errors, it seems that the error is "syntax error". You may have named the button in block 1 using a character that should not be used. Please check the text you wrote to "Block 1 button" in Block 1 settings in theme settings.
