### ISSUE TITLE
Front Page Block 7 - Available Courses - Shows Courses Which Should Be Hidden and Unavailable

### ISSUE THREAD

**Issue by lesbell** [themesalmond/moodle-theme_almondb#15]
As stated above, block 7 - Available Courses - on the default front page shows all courses, including those which are set to "Hidden" and should not be visible to students, etc. This occurs even when the front page is viewed by users who have not logged in, which is especially concerning. Such courses should not be visible to anyone except managers, course creators and teachers.

**Comment by themesalmond** [comment]
Hello,
We solved this in almond pro version.
https://shop.themesalmond.com/almond/

In the free version almondb theme, you can solve this problem as follows : 

- Update by making changes to the courses you want to appear. (So you have updated the course)
- Update all the courses you want to appear.
- A certain number of courses are already visible on the homepage. In this way, the courses you do not want will not appear while your last updated ones are displayed.
