### ISSUE TITLE
Menu items not appearing on the nav bar hamburger menu

### ISSUE THREAD

**Issue by davidspring** [themesalmond/moodle-theme_almondb#18]
I am using the AlmondB free Moodle theme. I have created four menu items which appear on the Home Page – similar to your AlmondB demo page. However, only the Home page appears as a link on the nav bar hamburger menu. This is different from your Demo page which shows that the courses and blog menu items appearing on the hamburger menu. How do I get menu items on the Main Menu to also appear on the hamburger menu?

**Comment by themesalmond** [comment]
Hello,
**Navigate to => Site Administration > Appearance > Themes > Almondb > Front Page > Front Page Header Choice >Front page nav link (Copy these.)** 

Then,
Navigate to => Site Administration > Appearance > Themes > Theme Settings > Custom menu items (paste here.)

**Comment by davidspring** [comment]
Thank you for the reply. I had done that. But the real problem was the z index which for some reason caused the hamburger menu to hide behind the slideshow on LG and XL screens. I added the following which solved the problem: 
To prevent the Hamburger menu from being covered by the slideshow on large and XL screens, add to the AlmondB theme Advanced tab custom CSS: 
**.drawer {z-index:99;}
.drawercontent {z-index:99;}**
Feel free to close this issue.

**Comment by davidspring** [comment]
PS I understand that by default, the hamburger menu does not display on LG and XL screens. But I had changed the header2.mustache file to have the hamburger menu appear on all screen widths.

**Comment by themesalmond** [comment]
That's interesting. Can you share your domain address with us?
