### ISSUE TITLE
Social Links do not display

### ISSUE THREAD

**Issue by Boakyesn** [themesalmond/moodle-theme_almondb#19]
The social links do not get displayed in the latest version of Moodle

**Comment by Boakyesn** [comment]
![image](https://github.com/themesalmond/moodle-theme_almondb/assets/60502570/13e3bf74-58bd-4cd9-ac30-e30dc36622db)
It changes to just bullet

**Comment by themesalmond** [comment]
Which moodle version are you using?

**Comment by Boakyesn** [comment]
Version 4.2
![image](https://github.com/themesalmond/moodle-theme_almondb/assets/60502570/47a84c1a-c1a7-4c70-9a86-bafe1f641c81)

**Comment by themesalmond** [comment]
https://moodle.org/plugins/theme_almondb/versions

Please install the latest update from here. We fixed this issue in our last update.

**Comment by Boakyesn** [comment]
It is fine now. Thank you
