### ISSUE TITLE
I have a question about your moodle theme almondb

### ISSUE THREAD

**Issue by suzie-sus** [themesalmond/moodle-theme_almondb#20]
Hi! How are you? I hope you good! 
So, i install your theme almondb im my moodle accout and i am trying to change the block "logo and login" and put these object on top of the carrossel image block. Can I change this kind of thing or dont? Please, can you help me with that?

**Comment by themesalmond** [comment]
Hello,
Navigate to > Site Administration > Appearance > Theme > Almondb > Front Page > Front Page Header Choice > Front Page Nav

You can change to header design here.

**Comment by suzie-sus** [comment]
thank you so much!
