### ISSUE TITLE
Sub-nemu in Almond theme in Moodle 4.1

### ISSUE THREAD

**Issue by frs2022** [themesalmond/moodle-theme_almondb#21]
Dear All, 
I hope you are doing well. 

We are customizing the sub-menu in our moodle 4.0. 

We notes that the **sub-menu** doesn't show in the Almond theme:

This example how we Custom menu items, the sub-menu " Hardware,Software" not shown:

Support
-IT
-- Hardware| /course/index.php?categoryid=105
-- Software | /course/index.php?categoryid=62

Anyone can help and advice, please.

Thank you

**Comment by themesalmond** [comment]
Hello,
There is no such thing in moodle itself.
