### ISSUE TITLE
frontpage navigation for admin

### ISSUE THREAD

**Issue by gerasim8774** [themesalmond/moodle-theme_almondb#23]
Hello! How can I add a link "Administration" in header for a frontpage, but just for admin certainly. Like in Boost theme for example

**Comment by themesalmond** [comment]
Navigate to Site Administration > Appearance > Theme settings > User menu items > Add this 

**administrationsite,moodle|/admin**

![image](https://github.com/themesalmond/moodle-theme_almondb/assets/107366277/a2b8bd91-114d-43e3-a097-3c7ed82c8cc2)
