### ISSUE TITLE
Accents is not working  block-3

### ISSUE THREAD

**Issue by isimbad** [themesalmond/moodle-theme_almondb#24]
Good morning
I have an issue in block-3 Features, that block is not accepting accents and  is not recognizing space replacing for !nbsp;, what can i do to surpass this?
Forgive my english.

**Comment by themesalmond** [comment]
Where exactly are you trying to add it in block? 
You can only add this in html sections in blocks.

**Comment by isimbad** [comment]
I'm trying add it in the block caption

**Comment by themesalmond** [comment]
You can only add this in html sections in blocks. You can't add to block caption
