### ISSUE TITLE
Using moodle functions (course) on the frontpage

### ISSUE THREAD

**Issue by All0ne** [themesalmond/moodle-theme_almondb#27]
Dear Almond-Team,
thanks a lot for your great theme =)
I would like to use on the frontpage the moodle activities and so on, especially the functions of moodle to display different content depending on the user type after login.

Is it possible to use the standard frontpage from Moolde instead of your frontpage? Or a combination, so that this standard frontpage-course is displayed for example under your great slider?

Thanks a lot and best regards

Translated with www.DeepL.com/Translator (free version)

**Comment by themesalmond** [comment]
Hello,
Thank you for supporting us.
We don't understand what you say exactly.
Almondb shows your existing moodle courses on the homepage. 
You can't change the front page view by user type every time.
