### ISSUE TITLE
Teacher name is missing in courses categories

### ISSUE THREAD

**Issue by aymannoor82** [themesalmond/moodle-theme_almondb#28]
Dears

When we press on i beside the course name it should display the summary with teacher name, but when we using almond theme it do nothing.

BR

**Comment by themesalmond** [comment]
Hello,
Can you share a screenshot with us?

**Comment by aymannoor82** [comment]
Hello @themesalmond 

Please see the attached two imgs the first is from Almond theme and the second from others themes (When we press on i ).


[img1](https://drive.google.com/file/d/1rPYRhHo-k0CkuayIbSJ4F5GDWCe4lYQj/view?usp=share_link)

[img2](https://drive.google.com/file/d/1oDZbtOgvjBVai9Lrpd6F0-ZtR-5_zIL1/view?usp=share_link)
BR

**Comment by themesalmond** [comment]
Hello,
Thank you for your feedback. 
We will fix this by releasing an update soon.
Best Regards
