### ISSUE TITLE
Front Page Header Background Color Bug

### ISSUE THREAD

**Issue by taylorbadraun** [themesalmond/moodle-theme_almondb#30]
Hello I have Moodle Version 4.2.1 installed and I can't get the Front Page header background color to change from transparent.  I've changed the Navbar back colour setting (theme_almondb | navbarcolor) and nothing changes.  All other Front Page Header settings work, to include Front page light-dark.  Any help or advice would be greatly appreciated. 

Thanks,

Taylor

**Comment by themesalmond** [comment]
Theme is working fine for us right now. You can download the theme again and install it from the beginning.
Can you share your website with us? 
Best Regards
