### ISSUE TITLE
FrontPage Blocks configuration not showing

### ISSUE THREAD

**Issue by tpitz** [themesalmond/moodle-theme_almondb#32]
Hi,

I cannot access to the FrontPage Blocks configuration under Site Administration. 
The tab is correctly showing but when I click on it, nothing happens. I confirm the url is /admin/settings.php?section=themesettingalmondb#theme_almondb_block, but the content rendered below is the content from the first tab. See below:
<img width="710" alt="Capture d’écran 2024-01-12 à 01 26 27" src="https://github.com/themesalmond/moodle-theme_almondb/assets/28119041/1aa27180-c625-46af-90c9-8d8069d50769">

After enabling max debugging errors, the following error appears as I refresh the homepage:
`Warning: foreach() argument must be of type array|object, null given in /bitnami/moodle/theme/almondb/lib/frontpage_block.php on line 298`
<img width="710" alt="Capture d’écran 2024-01-12 à 01 25 17" src="https://github.com/themesalmond/moodle-theme_almondb/assets/28119041/888726a7-86b3-4da2-aefd-f70c366a9a19">

I'm using Moodle version 4.3 and I deployed it on a GKE (kubernetes managed by GCP) with Helm, so it won't be effortless to add code into the docker image.

Thank's for helping.

Terry

**Comment by themesalmond** [comment]
Hello,
If you are building a live system, you need to normalize the following setting.
![image](https://github.com/themesalmond/moodle-theme_almondb/assets/107366277/a0f0c923-cffc-487c-86f7-60b01c0942d7)

Please define a course and category.
The error will disappear after defining the course and category.

Contact us if it still persists.

Best Regards
Almond Themes

**Comment by tpitz** [comment]
Hi,

I created courses and categories and the errors correctly disappeared.

But I still can't access to the FrontPage Blocks tab in the theme settings. It means I cannot rearrange FrontPage's structure, I'm stuck and don't know how to resolve this.

**Comment by themesalmond** [comment]
Hello,
Please don't forget to clear the cache this is an important step after your changes on Moodle.
Navigate to → Site administration > Development > Purge all cache

support@themesalmond.com
You can contact us at the e-mail address.
If you give us an admin login, we can investigate the error.

Best Regards
Almond Themes
