### ISSUE TITLE
Course Header Text Scaling for Mobile

### ISSUE THREAD

**Issue by estdillon** [themesalmond/moodle-theme_almondb#33]
Good day,

If you have a course with a certain length of text as well as a course image, the course text doesn't scale with the image, which results in a horizontal scroll. See image below:

<img width="627" alt="Screenshot 2024-01-22 at 10 05 44" src="https://github.com/themesalmond/moodle-theme_almondb/assets/123063215/b45786fe-8803-40cb-9ea5-504717bccab7">

A suggestion might be to move the [course-header-txt code](https://github.com/themesalmond/moodle-theme_almondb/blob/main/templates/theme_boost/drawers.mustache#L135C21-L137C27) inside of the [course-header-image code](https://github.com/themesalmond/moodle-theme_almondb/blob/main/templates/theme_boost/drawers.mustache#L132) so that it scales with the image. Then change the [.course-header-txt](https://github.com/themesalmond/moodle-theme_almondb/blob/main/scss/almondb/dashboard/_course.scss#L29) class to:

`.course-header-txt {
    position: relative;
    display: block;
    top: 10%;
    padding: 10px;
    margin-left: 2%;
    margin-right: 2%;
    background-color: cornsilk;
    border-radius: 5px;
}`

However, this does present the case that the background of the text (show by the cornsilk colour) will extend further than the name of the course itself when in desktop view. So, I'm not sure which situation is the most ideal.

You could also use a media query and set the width to 89% but still, leaves us with the same issue.

Hope this helps!

Regards,
Dillon

**Comment by themesalmond** [comment]
Hello,
We fixed this.
We published upgrade for Almondb.
You can upgrade theme.

Best Regards
Almond Themes
