### ISSUE TITLE
Block on home page

### ISSUE THREAD

**Issue by DanielSulea** [themesalmond/moodle-theme_almondb#34]
Hello,

I am contacting you because we are experimenting issues with the blocks that we use in our home page. 

For example: we want to change the colour background of the arrows and change the height of block 09 by using the scss code and the code does not respond to our needs.
We are writing the code in Almondb / Advanced settings / Raw SCSS
![Arrows and header - same color](https://github.com/themesalmond/moodle-theme_almondb/assets/66712560/22fdba53-67ce-4d03-b6b3-3488325e8465)

We have noticed that when we change the header color, it changes also the arrow background.
![Front Page Header](https://github.com/themesalmond/moodle-theme_almondb/assets/66712560/4272a0f3-9768-4907-8a8b-bc13b27b1b5a)

We have tested with inspect element and we could change the arrows background color only (without the header color to be also changed). We have tested also local, and it also worked.

Do you think that you could guide us with this issue?

Thank you in advance.

Kind regards,
Daniel

**Comment by themesalmond** [comment]
Hello,

You can use below code.
You can set height what you want.

.block09 .splide__arrow {
    background: transparent !important;
}
.block09 .single-box {
    height: 250px !important;
}

Best Regards
Almond Themes

**Comment by DanielSulea** [comment]
Thank you from our side. It works well.

**Comment by themesalmond** [comment]
By the way, we are trying to send you a reply via e-mail, but it is not sent to your e-mail address.
So even though we answered your support question, it was probably never communicated to you.
It might be good if you check.

Best Regards
Almond Themes
