### ISSUE TITLE
ReCAPTCHA

### ISSUE THREAD

**Issue by DanielSulea** [themesalmond/moodle-theme_almondb#38]
Hello,

I have installed the ContactForm and FilterCodes plugins.

Now I am trying to add the ReCAPTCHA to the contact form created and is not shown.

I cannot find the ReCAPTCHA setting to enable it: Local Plugins > Contact Form

![image](https://github.com/themesalmond/moodle-theme_almondb/assets/66712560/c952ec0e-a855-49c0-af44-689aacc6f9ca)

Found this KBA:
https://moodle.org/plugins/local_contact

![moodle-local-contact-settings](https://github.com/themesalmond/moodle-theme_almondb/assets/66712560/99efd04f-1edb-4044-88fe-56af17263c1a)

I have used {formcontactus} and also {recaptcha}. Unfortunately ReCAPTCHA is not displayed:

![Capture](https://github.com/themesalmond/moodle-theme_almondb/assets/66712560/43d2c413-272f-4c94-a99a-d4e22f6924b8)

We are using the AlmondB Theme.

Could you please advise how to solve this issue?

Thank you.

Kind regards,
Daniel

**Comment by DanielSulea** [comment]
This is the Almondb Theme and I think is belonging to you, right?

Thank you,
Daniel

**Comment by themesalmond** [comment]
Hello,
Almondb theme belongs to us.
But the plugins you mentioned above have no connection with us. 
You should notify them of any errors in the plugin.

Best Regards
Almond Themes

**Comment by DanielSulea** [comment]
Hello,

ok, thank you very much for your reply.

I will check with the plugin developers.

Sorry for the confusion.

Kind regards,
Daniel
