### ISSUE TITLE
theme_almondb_frontpageblock07 does not check for course visibility and is nasty on performance

### ISSUE THREAD

**Issue by danmarsden** [themesalmond/moodle-theme_almondb#5]
This function seems to display all courses - even courses the user should not be able to see and is extremely in-efficient - you need to rework this function so that it does not make so many db calls. - think about an example where a site might have 10,000 courses.

**Comment by themesalmond** [comment]
We fixed issues. Thank you for your help.

**Comment by jrsaw** [comment]
I saw the same thing, I ended up commenting out that (block-7 Available Courses) and used Block-2 Icon Box for the same idea.
