### ISSUE TITLE
invalid copyright statements

### ISSUE THREAD

**Issue by danmarsden** [themesalmond/moodle-theme_almondb#7]
Please review the "copyright" statements - you need to make sure it's clear which files you wrote, and which files are based on others.

for example - I know that Frédéric did not write this file:
https://github.com/themesalmond/almondb/blob/main/version.php#L21

in some simple files (like this one) - you should have your own name there.

in other files like this one:
https://github.com/themesalmond/almondb/blob/main/classes/output/core_renderer.php#L29

you should say something like "based on boost theme, and put your name in there too."

**Comment by themesalmond** [comment]
fixed
